---
BadNets:
  y_target: 1
  poisoning_rate: 0.10
  # pattern = torch.zeros((28, 28), dtype=torch.uint8)
  # pattern[-3:, -3:] = 255
  # weight = torch.zeros((28, 28), dtype=torch.float32)
  # weight[-3:, -3:] = 1.0
  pattern: 
    - -3
    - -3
  weight: 1.0
  poisoned_transform_index: 0
  train_schedule: null
  work_dir: null
 
 



    
